---
# tasks file for investigate
- name: install investigation tools
  package:
    name: "{{ investigate_packages }}"
    state: present
  register: investigate_install_investigate
  until: investigate_install_investigate is succeeded
  retries: 3
