---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
lint:
  name: yamllint
driver:
  name: docker
platforms:
  - name: investigate-ubuntu-latest
    image: ubuntu:latest
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: ubuntu-latest
